### ISSUE TITLE
Enabling Appender causes console output change and halts program

### ISSUE THREAD

**Issue by buckstephenh** [AlanBarber/log4net.Appender.Splunk#1]
Using identical appender suggested in your test.  

 ```
<appender name="SplunkHTTP" type="log4net.Appender.Splunk.SplunkHttpEventCollector, log4net.Appender.Splunk">
      <ServerUrl>http://myiporhost:8088/services/collector</ServerUrl>
      <Token>mytoken</Token>
      <RetriesOnError>0</RetriesOnError>
      <threshold value="DEBUG" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%message" />
      </layout>
    </appender>
```
My expectation is that the console output would remain unaffected whether or not this appender is engaged, and that application performance would be unaffected.  Any help would be appreciated!

**Comment by AlanBarber** [comment]
the halting issue should be fixed, i removed code that would throw an error if it was unable to actually connect to the splunk server. there is a new version published 2.0.0 with fixed code and the project has been upgraded to be a .NET Standard 2.0 library.
