### ISSUE TITLE
TLS Version mismatch issue

### ISSUE THREAD

**Issue by AbdulNasertp** [AlanBarber/log4net.Appender.Splunk#17]
We are trying to use this nuget package to sent logevent to Splunk HEC.
This works fine locally on developer machine, when we deploy the asp.net WebAPI dotnet version 4.8 on azure app service
its not working, we don't see the logs in Splunk HEC.

I downloaded the project and tried to figure out what might cause the issue, I was able to identify that the issue is with httpClient
TLS issue version not setting to TLS 1.2.

Error message: The underlying connection was closed: An unexpected error occurred on a send.

I modified the httpClient to always user TLS12 and took the modified DLL and referred in WebAPI project and deployed to app service and it worked!
var handler = new HttpClientHandler();
handler.SslProtocols = System.Security.Authentication.SslProtocols.Tls12;
httpClient = new HttpClient(handler,true);

It will be very help if a configuration parameter is provided to set the TLS version.

I would like to understand use of ignoreCertificateErrors, the certificate issue with Splunk server or the application
from where the Splunk HEC is called?

Thank you

**Comment by AbdulNasertp** [comment]
Done the following code change, as not a contributor not able to raise pull request:
using System.Security.Authentication;


// setup HTTP client
            if (ignoreCertificateErrors)
            {
                var certificateHandler = new HttpClientHandler();
                certificateHandler.ClientCertificateOptions = ClientCertificateOption.Manual;
                certificateHandler.ServerCertificateCustomValidationCallback = (httpRequestMessage, cert, cetChain, policyErrors) => true;
                certificateHandler.SslProtocols = SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls;
                httpClient = new HttpClient(certificateHandler, true);
            }
            else
            {
                var handler = new HttpClientHandler();
                handler.SslProtocols = SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls;
                httpClient = new HttpClient(handler,true);            
            } 

This might resolve the issue

**Comment by shelly-liabraaten-smarsh** [comment]
I would also like to take advantage of this change, and it looks like it's been merged into the master branch. Any update on when the next major version will be released?

**Comment by AbdulNasertp** [comment]
I don't see these changes are merged to the Master branch.

**Comment by AlanBarber** [comment]
should be fixed with the 2.2.0 release

https://www.nuget.org/packages/log4net.Appender.Splunk/2.2.0
