### ISSUE TITLE
Customize layout or add properties?

### ISSUE THREAD

**Issue by VictorioBerra** [AlanBarber/log4net.Appender.Splunk#18]
Whatever I do to the layout seems to be completely ignored when it gets into Splunk.

I need to add `method`, `type`, `line`, custom properties on **LogicalThreadContext** to the JSON that gets sent to Splunk.

Is there a way to tell this appender to pull those in?

**Comment by VictorioBerra** [comment]
Looking through the code now, it seems like logEvent.RenderedMessage _should_ be the final message after going through the layout stuff but in my Splunk instance, but its not. When I get it, this is what I see:

![image](https://user-images.githubusercontent.com/2934507/107830537-a8667e80-6d51-11eb-8595-a696ecf5500a.png)

**Comment by AlanBarber** [comment]
Can you share how your log4net config is setup?

**Comment by VictorioBerra** [comment]
I ended up switching to Serilog. Thanks for your reply though @AlanBarber
