### ISSUE TITLE
Could you please publish version 2.2 in NuGet

### ISSUE THREAD

**Issue by janvesely-nable** [AlanBarber/log4net.Appender.Splunk#22]
Hi Alan
Thank you for merging my change. Could you please release it as version 2.2 I guess. 
I guess it would solve the other issue that version 2.1 is not actually available in Nuget.
Thanks
Jan

**Comment by AlanBarber** [comment]
I've published it, should be available shortly.

https://www.nuget.org/packages/log4net.Appender.Splunk/2.2.0
