### ISSUE TITLE
Cannot configure the index for sent events

### ISSUE THREAD

**Issue by sixlettervariables** [AlanBarber/log4net.Appender.Splunk#3]
We're trying to incorporate this into our product, and currently we're unable to ingest logs without setting the index for the metadata. I did not see any configurable option, nor was it obvious from the source how this could be done externally.

**Comment by AlanBarber** [comment]
I've merged in your changes and will be pushing out a new nuget build shortly.

Thanks for contributing!

**Comment by sixlettervariables** [comment]
@AlanBarber any update on the NuGet publish? Thanks!

**Comment by AlanBarber** [comment]
I'm sorry, i was working on making some other changes but been side tracked. I shelved my changes for now and just pushed out 2.1.0 with your changes.

should be live in the next hour or so.
