### ISSUE TITLE
could not log data into splunk using SplunkHttpEventCollector in Asp.Net Web applicaion

### ISSUE THREAD

**Issue by ravitiru** [AlanBarber/log4net.Appender.Splunk#5]
We are facing an issue logging into splunk using  SplunkHttpEventCollector in Asp.Net Web application. We are able to log using C# console application but not using web application. Do you have any sample DotNet web application ?

**Comment by AlanBarber** [comment]
are you using webforms or mvc? also have you had success just using log4net to write to a text file?

I've checked in an updated solution with a webforms project that is configured and working on my local for logging data as reference.

**Comment by ravitiru** [comment]
MVC

**Comment by ravitiru** [comment]
Here is the code I am using 
-------------------------------------
 public static class ServiceLogger
    {
        public static readonly ILog log = LogManager.GetLogger("ServiceLogger");
        //public static readonly ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        static ServiceLogger()
        {
            //configure Log4Net to log the message
            log4net.Config.XmlConfigurator.Configure();
            //log4net.Config.XmlConfigurator.Configure(new FileInfo("log4net.config"));
        }
    }
-------------------------------------
 ServiceLogger.log.Debug("Web This is a debug log message");
-------------------------------------
    <appender name="Splunk" type="log4net.Appender.Splunk.SplunkHttpEventCollector, log4net.Appender.Splunk">
      <ServerUrl>https://xxxxxxxxxxx:8088</ServerUrl>
      <Token>xxxxxxxxxxxxxx</Token>
      <RetriesOnError>2</RetriesOnError>
      <layout type="log4net.Layout.XmlLayoutSchemaLog4j">
        <locationInfo value="true" />
      </layout>
    </appender>

    <root>
      <level value="ALL" />
      <appender-ref ref="Splunk" />
    </root>
---------------------------
Please help!
Thanks,
Ravi

**Comment by AlanBarber** [comment]
I noticed your config has https, are you using a valid, not the self-signed it uses by default, cert that is setup with the HEC?

https://answers.splunk.com/answers/462131/securing-http-event-collector.html

If the cert isn't valid it will not work with https enabled due to the .NET platform not allowing https connections to invalid certs.

**Comment by ravitiru** [comment]
This is enterprise level splunk server. It has a valid certificate. I am
able to write using console application but not using web application. In
your examples I see a console application. could you provide as sample Asp
>net application ?
Thank you,
Ravi

**Comment by AlanBarber** [comment]
I've added demo projects for asp.net webforms and asp.net mvc that work for me.
